######################################################################
# Automatically generated by qmake (2.01a) Thu Apr 5 21:16:07 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += classes.h mainwindow.h
FORMS += mainwindow.ui
SOURCES += classes.cpp main.cpp mainwindow.cpp
